---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.httpd.name }}-service
  labels:
    app: {{ .Values.httpd.name }}
    service: {{ .Values.httpd.name }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: {{ .Values.httpd.name }}
