apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.ldapadmin.name }}-service
    labels:
      app: {{ .Values.ldapadmin.name }}
      service: {{ .Values.ldapadmin.name }}
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
      name: http
  selector:
    app: {{ .Values.ldapadmin.name }}
