apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.nominatim.name }}-service
    labels:
      app: {{ .Values.nominatim.name }}
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 8080
      name: http
  selector:
    app: {{ .Values.nominatim.name }}
