apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.openldap.name }}-service
    labels:
      app: {{ .Values.openldap.name }}
      service: {{ .Values.openldap.name }}
spec:
  type: ClusterIP
  ports:
    - targetPort: 389
      port: 389
      name: http
  selector:
    app: {{ .Values.openldap.name }}
