---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgis.name }}-service
  labels:
    app: {{ .Values.postgis.name }}
    service: {{ .Values.postgis.name }}
spec:
  ports:
  - name: http
    port: 5432
    targetPort: 5432
  selector:
    app: {{ .Values.postgis.name }}
