---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sphinx.name }}-service
  labels:
    app: {{ .Values.sphinx.name }}
    service: {{ .Values.sphinx.name }}
spec:
  ports:
  - name: http
    port: 9306
    targetPort: 9306
  selector:
    app: {{ .Values.sphinx.name }}
