apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.wildfly.name }}-console-service
    labels:
      app: {{ .Values.wildfly.name }}
      service: {{ .Values.wildfly.name }}
spec:
  type: LoadBalancer
  ports:
    - targetPort: 9990
      port: 9990
      # nodePort: 30999
      name: wildfly-console
  selector:
    app: {{ .Values.wildfly.name }}
