apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wso2is.name }}-service
  labels:
    app: {{ .Values.wso2is.name }}
    service: {{ .Values.wso2is.name }}
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 9443
    # nodePort: 30443
    targetPort: 9443
  selector:
    app: {{ .Values.wso2is.name }}
