kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.nominatim.name }}-db-pv-claim
spec:
  storageClassName: {{ .Values.nominatim.pvc.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nominatim.pvc.dbSize }}
