kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.openldap.name }}-config-pv-claim
spec:
  storageClassName: {{ .Values.openldap.pvc.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.openldap.pvc.configSize }}
