apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafka.name }}-deployment
  labels:
    app: {{ .Values.kafka.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.kafka.name }}
  replicas: {{ .Values.kafka.replicaCounts }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.name }}
    spec:
      containers:
      - name: {{ .Values.kafka.name }}
        image: {{ .Values.kafka.image.repository }}
        imagePullPolicy: {{ .Values.kafka.pullPolicy }}
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 2Gi
        ports:
          - containerPort: 9092
            protocol: TCP
      imagePullSecrets:
      - name: {{ .Values.isbuilder.image.pullSecrets }}
      serviceAccountName: {{ .Release.Name }}-svc-account
      restartPolicy: Always
