apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.projection.name }}-deployment
  labels:
    app: {{ .Values.projection.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.projection.name }}
  replicas: {{ .Values.projection.replicaCounts }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.projection.name }}
    spec:
      containers:
      - name: {{ .Values.projection.name }}
        image: {{ .Values.projection.image.repository }}
        imagePullPolicy: {{ .Values.projection.pullPolicy }}
        args:
        - java
        - -server
        - -Xms64M
        - -Xmx512M
        - -Djava.library.path=/usr/lib/java/gdal/
        - -Dfile.encoding={{ .Values.isbuilder.encoding }}
        - -jar
        - /usr/isbuilder/projection.jar
        - --spring.profiles.active=production
        - --server.port=8080
        - --ds.host={{ .Values.datasource.host }}
        - --ds.port={{ .Values.datasource.port }}
        - --ds.database={{ .Values.datasource.database }}
        - --ds.user={{ .Values.datasource.username }}
        - --ds.password={{ .Values.datasource.password }}
        - --keycloak.auth-server-url={{ .Values.keycloak.auth_server }}
        - --keycloak.realm={{ .Values.keycloak.realm }}
        - --keycloak.resource={{ .Values.keycloak.resource }}
        - --projection.init=true
        - --flyway.enabled=false
        resources:
          requests:
            memory: 64Mi
          limits:
            memory: 512Mi
        ports:
          - containerPort: 8080
            protocol: TCP
      imagePullSecrets:
      - name: {{ .Values.isbuilder.image.pullSecrets }}
      serviceAccountName: {{ .Release.Name }}-svc-account
      restartPolicy: Always
