apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.raster.name }}-deployment
  labels:
    app: {{ .Values.raster.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.raster.name }}
  replicas: {{ .Values.raster.replicaCounts }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.raster.name }}
    spec:
      containers:
      - name: {{ .Values.raster.name }}
        image: {{ .Values.raster.image.repository }}
        imagePullPolicy: {{ .Values.raster.pullPolicy }}
        args:
        - java
        - -server
        - -Xms64M
        - -Xmx2064M
        - -Dfile.encoding={{ .Values.isbuilder.encoding }}
        - -jar
        - /usr/isbuilder/raster.jar
        - --spring.profiles.active=production
        - --server.port=8080
        - --spring.profiles.active=production
        - --ds.host={{ .Values.datasource.host }}
        - --ds.port={{ .Values.datasource.port }}
        - --ds.database={{ .Values.datasource.database }}
        - --ds.user={{ .Values.datasource.username }}
        - --ds.password={{ .Values.datasource.password }}
        - --keycloak.auth-server-url={{ .Values.keycloak.auth_server }}
        - --keycloak.realm={{ .Values.keycloak.realm }}
        - --keycloak.resource={{ .Values.keycloak.resource }}
        - --ds.host.core={{ .Values.ds_core.host }}
        - --ds.database.core={{ .Values.ds_core.database }}
        - --ds.user.core={{ .Values.ds_core.username }}
        - --ds.password.core={{ .Values.ds_core.password }}
        - --isbuilder.url=http://core-service:8080
        - --flyway.enabled=false
        resources:
          requests:
            memory: 64Mi
          limits:
            memory: 256Mi
        ports:
          - containerPort: 8080
            protocol: TCP
      imagePullSecrets:
      - name: {{ .Values.isbuilder.image.pullSecrets }}
      serviceAccountName: {{ .Release.Name }}-svc-account
      restartPolicy: Always
