---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.access_token.name }}-service
  labels:
    app: {{ .Values.access_token.name }}
    service: {{ .Values.access_token.name }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: {{ .Values.access_token.name }}
